// Code generated by qtc from "navigation.qtpl.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package components

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamNavigation(qw422016 *qt422016.Writer, menuItems []*MenuItem, active *MenuItem) {
	qw422016.N().S(`
<script>
  const toggleMobileMenu = () => {
    document.getElementById("mobile-menu-cover").classList.toggle("open");
    document.getElementById("menu-panel").classList.toggle("open");
  };
</script>

<ul id="bar">
  <li><a href="/">Walrss</a></li>
  <li class="float-right mobile-only"><span onclick="toggleMobileMenu()"><i class="bi bi-three-dots"></i></span></li>
</ul>

<ul id="menu-panel">
  `)
	for _, item := range menuItems {
		qw422016.N().S(`
    `)
		if item == active {
			qw422016.N().S(`
      <li class="active"><a class="active" href="`)
			qw422016.E().S(item.Path)
			qw422016.N().S(`"><i class="bi `)
			qw422016.E().S(item.Icon)
			qw422016.N().S(`"></i> `)
			qw422016.E().S(item.Text)
			qw422016.N().S(`</a></li>
    `)
		} else {
			qw422016.N().S(`
      <li><a href="`)
			qw422016.E().S(item.Path)
			qw422016.N().S(`"><i class="bi `)
			qw422016.E().S(item.Icon)
			qw422016.N().S(`"></i> `)
			qw422016.E().S(item.Text)
			qw422016.N().S(`</a></li>
    `)
		}
		qw422016.N().S(`
  `)
	}
	qw422016.N().S(`
</ul>

<div id="mobile-menu-cover" onclick="toggleMobileMenu()"></div>
`)
}

func WriteNavigation(qq422016 qtio422016.Writer, menuItems []*MenuItem, active *MenuItem) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamNavigation(qw422016, menuItems, active)
	qt422016.ReleaseWriter(qw422016)
}

func Navigation(menuItems []*MenuItem, active *MenuItem) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteNavigation(qb422016, menuItems, active)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
