// Code generated by qtc from "categories.qtpl.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package neoviews

import "github.com/codemicro/walrss/walrss/internal/urls"

import "github.com/codemicro/walrss/walrss/internal/http/neoviews/internal/components"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func StreamFragmentNewCategory(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
`)
	components.StreamBeginModal(qw422016)
	qw422016.N().S(`
<h2><i class="bi bi-pencil-square"></i> Create New Category</h2>
<form>
    <div class="form-grid">
        <label for="new-category-name">Category name</label>
        <input type="text" id="new-category-name" name="name" placeholder="Name">
    </div>
    <div class="flex-horizontal pt">
        <button class="button green" hx-post="`)
	qw422016.E().S(urls.NewCategory)
	qw422016.N().S(`" hx-target="#modal-target">Submit</button>
        <button class="button red" hx-get="`)
	qw422016.E().S(urls.CancelModal)
	qw422016.N().S(`" hx-target="#modal-target">Cancel</button>
    </div>
</form>
`)
	components.StreamEndModal(qw422016)
	qw422016.N().S(`
`)
}

func WriteFragmentNewCategory(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamFragmentNewCategory(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func FragmentNewCategory() string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteFragmentNewCategory(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
