// Code generated by qtc from "layoutComponents.qtpl.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import "github.com/codemicro/walrss/walrss/internal/urls"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func streamnavbar(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
<nav class="navbar navbar-light mb-3" style="background-color: #EFCB68">
    <div class="container-fluid">
        <a class="navbar-brand" href="`)
	qw422016.N().S(urls.Index)
	qw422016.N().S(`">Walrss</a>
    </div>
</nav>
`)
}

func writenavbar(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	streamnavbar(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func navbar() string {
	qb422016 := qt422016.AcquireByteBuffer()
	writenavbar(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
