// Code generated by qtc from "main.qtpl.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import "github.com/codemicro/walrss/walrss/internal/db"

import "github.com/codemicro/walrss/walrss/internal/urls"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

type MainPage struct {
	BasePage
	EnableDigests bool
	SelectedDay   db.SendDay
	SelectedTime  int
}

func (p *MainPage) StreamTitle(qw422016 *qt422016.Writer) {
}

func (p *MainPage) WriteTitle(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamTitle(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *MainPage) Title() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteTitle(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *MainPage) StreamBody(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
`)
	streamnavbar(qw422016)
	qw422016.N().S(`

<div class="container">
    <h1>My settings</h1>

    <div class="card mt-3">
        <div class="card-header">
            Schedule
        </div>
        <div class="card-body">

            <div class="mb-2">
                <input
                        type="checkbox"
                        id="enableCheckbox"
                        name="enable"
                        `)
	if p.EnableDigests {
		qw422016.N().S(`checked`)
	}
	qw422016.N().S(`
                        hx-put="`)
	qw422016.N().S(urls.EditEnabledState)
	qw422016.N().S(`"
                        hx-indicator="#enableCheckboxIndicator"
                >
                <label for="enableCheckbox">Enable digest delivery</label>
                <i class="ml-2 iconLoading htmx-indicator" id="enableCheckboxIndicator"></i>
            </div>

            <form
                    class="row row-cols-lg-auto g-3 align-items-center"
                    hx-put="`)
	qw422016.E().S(urls.EditTimings)
	qw422016.N().S(`"
                    hx-indicator="#submitScheduleIndicator"
            >
                <div class="col-12">
                    Deliver my digests
                </div>

                <div class="col-12">
                    <label class="visually-hidden" for="daySelection">Day of week</label>
                    <select
                            class="form-select"
                            id="daySelection"
                            name="day"
                            `)
	if !p.EnableDigests {
		qw422016.N().S(`disabled`)
	}
	qw422016.N().S(`
                    >
                        `)
	for i := db.SendDaily; i <= db.SendOnSunday; i += 1 {
		qw422016.N().S(`
                            <option
                                    value="`)
		qw422016.N().D(int(i))
		qw422016.N().S(`"
                                    `)
		if p.SelectedDay == i {
			qw422016.N().S(`selected`)
		}
		qw422016.N().S(`
                            >
                                `)
		if i != db.SendDaily {
			qw422016.N().S(`on `)
		}
		qw422016.E().S(i.String())
		qw422016.N().S(`
                            </option>
                        `)
	}
	qw422016.N().S(`
                    </select>
                </div>

                <div class="col-12">at</div>

                <div class="col-12">
                    <label class="visually-hidden" for="timeSelection">Time of day</label>
                    <select
                            class="form-select"
                            id="timeSelection"
                            name="time"
                            `)
	if !p.EnableDigests {
		qw422016.N().S(`disabled`)
	}
	qw422016.N().S(`
                    >
                        `)
	for i := 0; i <= 23; i += 1 {
		qw422016.N().S(`
                            <option
                                    value="`)
		qw422016.N().D(i)
		qw422016.N().S(`"
                                    `)
		if p.SelectedTime == i {
			qw422016.N().S(`selected`)
		}
		qw422016.N().S(`
                            >
                                `)
		qw422016.N().D(i)
		qw422016.N().S(`:00
                            </option>
                        `)
	}
	qw422016.N().S(`
                    </select>
                </div>

                <div class="col-12">UTC</div>

                <div class="col-12">
                    <button type="submit" class="btn btn-primary" `)
	if !p.EnableDigests {
		qw422016.N().S(`disabled`)
	}
	qw422016.N().S(`>Save</button>
                    <i class="iconLoading align-middle htmx-indicator" style="margin-left: 1rem; width: 2rem;" id="submitScheduleIndicator"></i>
                </div>
            </form>

        </div>
    </div>

    <div class="card mt-3">
        <div class="card-header">
            Feeds
        </div>
        <div class="card-body">

            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">First</th>
                    <th scope="col">Last</th>
                    <th scope="col">Handle</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>Mark</td>
                    <td>Otto</td>
                    <td>@mdo</td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>Jacob</td>
                    <td>Thornton</td>
                    <td>@fat</td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td colspan="2">Larry the Bird</td>
                    <td>@twitter</td>
                </tr>
                </tbody>
            </table>

        </div>
    </div>

</div>
`)
}

func (p *MainPage) WriteBody(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamBody(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *MainPage) Body() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteBody(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
