// Code generated by qtc from "main.qtpl.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import "github.com/codemicro/walrss/walrss/internal/db"

import "github.com/codemicro/walrss/walrss/internal/urls"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

type MainPage struct {
	BasePage
	EnableDigests bool
	SelectedDay   db.SendDay
	SelectedTime  int
}

func (p *MainPage) StreamTitle(qw422016 *qt422016.Writer) {
}

func (p *MainPage) WriteTitle(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamTitle(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *MainPage) Title() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteTitle(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *MainPage) StreamBody(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
<div class="position-fixed top end-0 p-3" style="z-index: 11">
    <div id="toast" class="toast align-items-center text-white bg-primary border-0" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body" id="toastBody">
                Hello, world! This is a toast message.
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
</div>

`)
	streamnavbar(qw422016)
	qw422016.N().S(`

<script>
    let toast = document.getElementById("toast")
    let toastBody = document.getElementById("toastBody")

    function showToast(delay) {
        new bootstrap.Toast(toast, {delay: delay}).show();
    }

    function errorHandler() {
        toastBody.innerText = "Internal error: action incomplete";
        toast.classList.remove("bg-success")
        toast.classList.add("bg-danger")
        showToast(5000)
    }

    document.body.addEventListener("htmx:sendError", errorHandler);
    document.body.addEventListener("htmx:responseError", errorHandler);

    document.body.addEventListener("successResponse", function () {
        toastBody.innerText = "Success!"
        toast.classList.remove("bg-danger")
        toast.classList.add("bg-success")
        showToast(1500)
    })
</script>

<div class="container">
    <h1>My settings</h1>

    `)
	p.StreamRenderScheduleCard(qw422016)
	qw422016.N().S(`

    <div class="card mt-3">
        <div class="card-header">
            Feeds
        </div>
        <div class="card-body">

            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">First</th>
                    <th scope="col">Last</th>
                    <th scope="col">Handle</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>Mark</td>
                    <td>Otto</td>
                    <td>@mdo</td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>Jacob</td>
                    <td>Thornton</td>
                    <td>@fat</td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td colspan="2">Larry the Bird</td>
                    <td>@twitter</td>
                </tr>
                </tbody>
            </table>

        </div>
    </div>

</div>
`)
}

func (p *MainPage) WriteBody(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamBody(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *MainPage) Body() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteBody(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *MainPage) StreamRenderScheduleCard(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
<div class="card mt-3" id="scheduleCard" hx-target="this" hx-swap="outerHTML">
    <div class="card-header">
        Schedule
    </div>
    <div class="card-body">

        <div class="mb-2 row row-cols-lg-auto align-items-center">
            <div class="col-12">
                <input
                        type="checkbox"
                        id="enableCheckbox"
                        name="enable"
                        `)
	if p.EnableDigests {
		qw422016.N().S(`checked`)
	}
	qw422016.N().S(`
                        hx-put="`)
	qw422016.N().S(urls.EditEnabledState)
	qw422016.N().S(`"
                        hx-indicator="#enableCheckboxIndicator"
                >
                <label for="enableCheckbox">Enable digest delivery</label>
            </div>

            <div class="col-12">
                <div class="spinner-border spinner-border-sm request-indicator align-middle" style="width: 1rem; height: 1rem;" role="status" id="enableCheckboxIndicator">
                    <span class="visually-hidden">Loading...</span>
                </div>
            </div>
        </div>

        <form
                class="row row-cols-lg-auto g-3 align-items-center"
                hx-put="`)
	qw422016.E().S(urls.EditTimings)
	qw422016.N().S(`"
                hx-indicator="#submitScheduleIndicator"
        >
            <div class="col-12">
                Deliver my digests
            </div>

            <div class="col-12">
                <label class="visually-hidden" for="daySelection">Day of week</label>
                <select
                        class="form-select"
                        id="daySelection"
                        name="day"
                        `)
	if !p.EnableDigests {
		qw422016.N().S(`disabled`)
	}
	qw422016.N().S(`
                >
                    `)
	for i := db.SendDaily; i <= db.SendOnSunday; i += 1 {
		qw422016.N().S(`
                    <option
                            value="`)
		qw422016.N().D(int(i))
		qw422016.N().S(`"
                            `)
		if p.SelectedDay == i {
			qw422016.N().S(`selected`)
		}
		qw422016.N().S(`
                    >
                        `)
		if i != db.SendDaily {
			qw422016.N().S(`on `)
		}
		qw422016.E().S(i.String())
		qw422016.N().S(`
                    </option>
                    `)
	}
	qw422016.N().S(`
                </select>
            </div>

            <div class="col-12">at</div>

            <div class="col-12">
                <label class="visually-hidden" for="timeSelection">Time of day</label>
                <select
                        class="form-select"
                        id="timeSelection"
                        name="time"
                        `)
	if !p.EnableDigests {
		qw422016.N().S(`disabled`)
	}
	qw422016.N().S(`
                >
                    `)
	for i := 0; i <= 23; i += 1 {
		qw422016.N().S(`
                    <option
                            value="`)
		qw422016.N().D(i)
		qw422016.N().S(`"
                            `)
		if p.SelectedTime == i {
			qw422016.N().S(`selected`)
		}
		qw422016.N().S(`
                    >
                        `)
		qw422016.N().D(i)
		qw422016.N().S(`:00
                    </option>
                    `)
	}
	qw422016.N().S(`
                </select>
            </div>

            <div class="col-12">UTC</div>

            <div class="col-12">
                <button type="submit" class="btn btn-primary" `)
	if !p.EnableDigests {
		qw422016.N().S(`disabled`)
	}
	qw422016.N().S(`>Save</button>
            </div>

            <div class="col-12">
                <div class="spinner-border align-middle request-indicator" id="submitScheduleIndicator" style="width: 2rem; height: 2rem;" role="status">
                    <span class="visually-hidden">Loading...</span>
                </div>
            </div>
        </form>

    </div>
</div>
`)
}

func (p *MainPage) WriteRenderScheduleCard(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamRenderScheduleCard(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *MainPage) RenderScheduleCard() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteRenderScheduleCard(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
