// Code generated by qtc from "page.qtpl.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

type Page interface {
	Title() string
	StreamTitle(qw422016 *qt422016.Writer)
	WriteTitle(qq422016 qtio422016.Writer)
	Body() string
	StreamBody(qw422016 *qt422016.Writer)
	WriteBody(qq422016 qtio422016.Writer)
	HeadContent() string
	StreamHeadContent(qw422016 *qt422016.Writer)
	WriteHeadContent(qq422016 qtio422016.Writer)
}

// Page prints a page implementing Page interface.

func StreamRenderPage(qw422016 *qt422016.Writer, p Page) {
	qw422016.N().S(`
<!DOCTYPE html>
<html>
<head>
    <title>`)
	qw422016.N().S(makePageTitle(p))
	qw422016.N().S(`</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://unpkg.com/htmx.org@1.7.0"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <style>
        [disabled] {
            cursor: not-allowed;
        }

        .request-indicator {
            display:none;
        }
        .htmx-request .request-indicator{
            display: block;
        }
        .htmx-request.request-indicator{
            display: block;
        }

    </style>
    `)
	p.StreamHeadContent(qw422016)
	qw422016.N().S(`
</head>
<body>
`)
	p.StreamBody(qw422016)
	qw422016.N().S(`
<div class="pb-5"></div>
<p class="text-center text-secondary"><a href="https://github.com/codemicro/walrss" target="_blank" rel="noopener noreferrer">Walrss is open-source software</a> that's licensed under the <a href="https://github.com/codemicro/walrss/blob/master/LICENSE" target="_blank" rel="noopener noreferrer">GNU AGPL v3.</a></p>
</body>
</html>
`)
}

func WriteRenderPage(qq422016 qtio422016.Writer, p Page) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamRenderPage(qw422016, p)
	qt422016.ReleaseWriter(qw422016)
}

func RenderPage(p Page) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteRenderPage(qb422016, p)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

type BasePage struct{}

func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
}

func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamTitle(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *BasePage) Title() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteTitle(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *BasePage) StreamHeadContent(qw422016 *qt422016.Writer) {
}

func (p *BasePage) WriteHeadContent(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamHeadContent(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *BasePage) HeadContent() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteHeadContent(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func StreamProblemBox(qw422016 *qt422016.Writer, p string) {
	qw422016.N().S(`
<div class="alert alert-danger" role="alert">
    `)
	qw422016.N().S(p)
	qw422016.N().S(`
</div>
`)
}

func WriteProblemBox(qq422016 qtio422016.Writer, p string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamProblemBox(qw422016, p)
	qt422016.ReleaseWriter(qw422016)
}

func ProblemBox(p string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteProblemBox(qb422016, p)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func StreamSuccessBox(qw422016 *qt422016.Writer, p string) {
	qw422016.N().S(`
<div class="alert alert-success" role="alert">
    `)
	qw422016.N().S(p)
	qw422016.N().S(`
</div>
`)
}

func WriteSuccessBox(qq422016 qtio422016.Writer, p string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamSuccessBox(qw422016, p)
	qt422016.ReleaseWriter(qw422016)
}

func SuccessBox(p string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteSuccessBox(qb422016, p)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func StreamWarningBox(qw422016 *qt422016.Writer, p string) {
	qw422016.N().S(`
<div class="alert alert-warning" role="alert">
    `)
	qw422016.N().S(p)
	qw422016.N().S(`
</div>
`)
}

func WriteWarningBox(qq422016 qtio422016.Writer, p string) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	StreamWarningBox(qw422016, p)
	qt422016.ReleaseWriter(qw422016)
}

func WarningBox(p string) string {
	qb422016 := qt422016.AcquireByteBuffer()
	WriteWarningBox(qb422016, p)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

// PolyPage is used to create a basic page dynamically using Daz.

type PolyPage struct {
	BasePage
	TitleString      string
	BodyContent      string
	ExtraHeadContent string
}

func (p *PolyPage) StreamTitle(qw422016 *qt422016.Writer) {
	qw422016.N().S(p.TitleString)
}

func (p *PolyPage) WriteTitle(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamTitle(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *PolyPage) Title() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteTitle(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *PolyPage) StreamBody(qw422016 *qt422016.Writer) {
	streamnavbar(qw422016)
	qw422016.N().S(`<div class="container">`)
	qw422016.N().S(p.BodyContent)
	qw422016.N().S(`</div>`)
}

func (p *PolyPage) WriteBody(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamBody(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *PolyPage) Body() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteBody(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *PolyPage) StreamHeadContent(qw422016 *qt422016.Writer) {
	qw422016.N().S(p.ExtraHeadContent)
}

func (p *PolyPage) WriteHeadContent(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamHeadContent(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *PolyPage) HeadContent() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteHeadContent(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
