// Code generated by qtc from "register.qtpl.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package views

import "github.com/codemicro/walrss/walrss/internal/urls"

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

type RegisterPage struct {
	BasePage
	Problem string
}

func (p *RegisterPage) StreamTitle(qw422016 *qt422016.Writer) {
	qw422016.N().S(`Register`)
}

func (p *RegisterPage) WriteTitle(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamTitle(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *RegisterPage) Title() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteTitle(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *RegisterPage) StreamBody(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
`)
	streamnavbar(qw422016)
	qw422016.N().S(`

<div class="container">
    <h1>Register</h1>

    `)
	if p.Problem != "" {
		qw422016.N().S(`
        `)
		StreamProblemBox(qw422016, p.Problem)
		qw422016.N().S(`
    `)
	}
	qw422016.N().S(`

    <form action="" method="post">
        <div class="mb-3">
            <label for="emailInput" class="form-label">Email address</label>
            <input type="email" class="form-control" id="emailInput" name="email">
        </div>
        <div class="mb-3">
            <label for="passwordInput" class="form-label">Password</label>
            <input type="password" class="form-control" id="passwordInput" name="password">
        </div>
        <div class="mb-3">
            <label for="passwordConfirmation" class="form-label">Retype password</label>
            <input type="password" class="form-control" id="passwordConfirmation" name="passwordConfirmation">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <br>
    <a href="`)
	qw422016.N().S(urls.AuthSignIn)
	qw422016.N().S(`">Already got an account? Click here to sign in</a>
</div>
`)
}

func (p *RegisterPage) WriteBody(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamBody(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *RegisterPage) Body() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteBody(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
